import 'package:flutter/material.dart';
import 'package:read_more_fun/core/services/language_service.dart';

extension LocalizationExtension on BuildContext {
  String translate(String key, [List<String>? args]) {
    final lang = LanguageService.activeLanguageNotifier.value;
    String value = AppLocalizations.getValue(lang, key);
    if (args != null && args.isNotEmpty) {
      for (int i = 0; i < args.length; i++) {
        value = value.replaceAll('{$i}', args[i]);
      }
    }
    return value;
  }
}

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Read More Fun',
      'app_subtitle': 'Create WhatsApp Quiz, Spoiler, Joke, Pay-off, or General Intro of Business for longer messages with “... Read more” button',
      'advanced_settings': 'Advanced Spacing Settings',
      'spacing_count': 'Spacing Character Count: {0}',
      'spacing_note': 'Note: WhatsApp Web requires more spaces than mobile (Default: 1300)',
      'preset_custom': 'Custom',
      'preset_spoiler': 'Spoiler',
      'preset_joke': 'Joke',
      'preset_quiz': 'Quiz',
      'bold_tooltip': 'Bold',
      'italic_tooltip': 'Italic',
      'strikethrough_tooltip': 'Strikethrough',
      'free_text_intro_label': 'Enter Intro Text (*bold*, _italic_, ~strike~)',
      'free_text_intro_hint': 'Type introduction text here',
      'free_text_read_more_label': 'Read-more content (*bold*, _italic_, ~strike~)',
      'free_text_read_more_hint': 'This is really funny app.',
      'spoiler_q_label': 'Question / Setup (Visible)',
      'spoiler_q_hint': 'e.g. Who dies in Avengers: Infinity War?',
      'spoiler_a_label': 'The Spoiler (Hidden)',
      'spoiler_a_hint': 'e.g. Spider-Man turns to dust!',
      'joke_q_label': 'Joke Setup (Visible)',
      'joke_q_hint': 'e.g. Why don\'t scientists trust atoms?',
      'joke_a_label': 'Punchline (Hidden)',
      'joke_a_hint': 'e.g. Because they make up everything!',
      'quiz_q_label': 'Quiz Question (Visible)',
      'quiz_q_hint': 'e.g. What is the capital of Japan?',
      'quiz_o_label': 'Options (Visible, Optional)',
      'quiz_o_hint': 'e.g. A) Kyoto\nB) Tokyo\nC) Osaka',
      'quiz_a_label': 'Correct Answer (Hidden)',
      'quiz_a_hint': 'e.g. B) Tokyo',
      'message_preview': 'Message Preview:',
      'read_more_link': 'Read more',
      'button_copy': 'Copy',
      'button_whatsapp': 'WhatsApp',
      'button_templates': 'Templates',
      'button_history': 'History',
      'button_save': 'Save',
      'snackbar_copied': 'Copied to Clipboard',
      'snackbar_wait': 'Please wait...',
      'snackbar_sharing': 'Sharing App...',
      'snackbar_sharing_template': 'Sharing Template...',
      'templates_title': 'Templates',
      'search_templates': 'Search templates...',
      'no_templates_found': 'No templates found',
      'create_custom_template': 'Create Custom Template',
      'custom_template_saved': 'Custom template saved!',
      'fill_both_fields': 'Please fill in both fields.',
      'delete_template': 'Delete Template',
      'template_deleted': 'Template deleted',
      'share_template': 'Share Template',
      'select_language_title': 'Select Template Language',
      'change_language_title': 'Change Template Language',
      'history_title': 'Draft History',
      'no_history_yet': 'No history yet',
      'delete_draft': 'Delete Draft',
      'quiz_answer_prefix': 'Answer: {0}',
      'share_app_text': '*Try out the magic of WhatsApp*{0}\n\nHow\'s it? \n\nMake your own long text to short: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nCreated from: https://bit.ly/read-more-whatsapp',
      'share_app': 'Share App',
      'category_all': 'All',
      'category_confessions': 'Confessions',
      'category_spoiler_alert': 'Spoiler Alert',
      'category_pranks_glitches': 'Pranks & Glitches',
      'category_riddles_brainers': 'Riddles & Brainers',
      'category_millennial_work': 'Millennial Work Speak',
      'category_genz_sarcasm': 'GenZ Daily Sarcasm',
    },
    'hi': {
      'app_title': 'रीड मोर फन',
      'app_subtitle': 'व्हाट्सएप पर लम्बे संदेशों में "... Read more" बटन जोड़कर मजेदार पहेली, जोक्स या बिज़नेस परिचय बनाएं।',
      'advanced_settings': 'उन्नत अंतराल सेटिंग्स',
      'spacing_count': 'अंतराल वर्ण संख्या: {0}',
      'spacing_note': 'नोट: व्हाट्सएप वेब को मोबाइल से अधिक अंतराल की आवश्यकता होती है (डिफ़ॉल्ट: 1300)',
      'preset_custom': 'कस्टम',
      'preset_spoiler': 'स्पॉइलर',
      'preset_joke': 'जोक',
      'preset_quiz': 'क्विज़',
      'bold_tooltip': 'बोल्ड',
      'italic_tooltip': 'इटैलिक',
      'strikethrough_tooltip': 'स्ट्राइकथ्रू',
      'free_text_intro_label': 'परिचय पाठ दर्ज करें (*bold*, _italic_, ~strike~)',
      'free_text_intro_hint': 'यहाँ अपना परिचय पाठ लिखें',
      'free_text_read_more_label': 'रीड-मोर सामग्री (*bold*, _italic_, ~strike~)',
      'free_text_read_more_hint': 'यह बहुत ही मज़ेदार ऐप है।',
      'spoiler_q_label': 'प्रश्न / सेटअप (दृश्यमान)',
      'spoiler_q_hint': 'जैसे: एवेंजर्स में कौन मरता है?',
      'spoiler_a_label': 'स्पॉइलर (छिपा हुआ)',
      'spoiler_a_hint': 'जैसे: स्पाइडर-मैन धूल बन जाता है!',
      'joke_q_label': 'जोक सेटअप (दृश्यमान)',
      'joke_q_hint': 'जैसे: वैज्ञानिक परमाणुओं पर भरोसा क्यों नहीं करते?',
      'joke_a_label': 'पंचलाइन (छिपा हुआ)',
      'joke_a_hint': 'जैसे: क्योंकि वे सब कुछ खुद बनाते हैं!',
      'quiz_q_label': 'क्विज़ प्रश्न (दृश्यमान)',
      'quiz_q_hint': 'जैसे: जापान की राजधानी क्या है?',
      'quiz_o_label': 'विकल्प (दृश्यमान, वैकल्पिक)',
      'quiz_o_hint': 'जैसे: A) क्योटो\nB) टोक्यो\nC) ओसाका',
      'quiz_a_label': 'सही उत्तर (छिपा हुआ)',
      'quiz_a_hint': 'जैसे: B) टोक्यो',
      'message_preview': 'संदेश पूर्वावलोकन:',
      'read_more_link': 'और पढ़ें',
      'button_copy': 'कॉपी',
      'button_whatsapp': 'व्हाट्सएप',
      'button_templates': 'टेम्पलेट्स',
      'button_history': 'इतिहास',
      'button_save': 'सहेजें',
      'snackbar_copied': 'क्लिपबोर्ड पर कॉपी किया गया',
      'snackbar_wait': 'कृपया प्रतीक्षा करें...',
      'snackbar_sharing': 'ऐप साझा किया जा रहा है...',
      'snackbar_sharing_template': 'टेम्पलेट साझा किया जा रहा है...',
      'templates_title': 'टेम्पलेट्स',
      'search_templates': 'टेम्पलेट्स खोजें...',
      'no_templates_found': 'कोई टेम्पलेट नहीं मिला',
      'create_custom_template': 'कस्टम टेम्पलेट बनाएं',
      'custom_template_saved': 'कस्टम टेम्पलेट सहेजा गया!',
      'fill_both_fields': 'कृपया दोनों फ़ील्ड भरें।',
      'delete_template': 'टेम्पलेट हटाएं',
      'template_deleted': 'टेम्पलेट हटा दिया गया',
      'share_template': 'टेम्पलेट साझा करें',
      'select_language_title': 'टेम्पलेट भाषा चुनें',
      'change_language_title': 'टेम्पलेट भाषा बदलें',
      'history_title': 'ड्राफ्ट इतिहास',
      'no_history_yet': 'अभी तक कोई इतिहास नहीं',
      'delete_draft': 'ड्राफ्ट हटाएं',
      'quiz_answer_prefix': 'उत्तर: {0}',
      'share_app_text': '*व्हाट्सएप के जादू को आज़माएं*{0}\n\nयह कैसा लगा? \n\nअपने लम्बे टेक्स्ट को छोटा बनाएं: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nसृजित: https://bit.ly/read-more-whatsapp',
      'share_app': 'ऐप साझा करें',
      'category_all': 'सभी',
      'category_confessions': 'स्वीकारोक्ति (Crush)',
      'category_spoiler_alert': 'स्पॉइलर अलर्ट',
      'category_pranks_glitches': 'शरारत (Pranks)',
      'category_riddles_brainers': 'पहेलियां',
      'category_millennial_work': 'ऑफिस लफ़्ज़ (Work)',
      'category_genz_sarcasm': 'रोज़ाना व्यंग्य (GenZ)',
    },
    'gu': {
      'app_title': 'રીડ મોર ફન',
      'app_subtitle': 'વોટ્સએપ પર લાંબા મેસેજીસમાં "... Read more" બટન ઉમેરીને રમુજી કોયડાઓ, જોક્સ અથવા વ્યવસાયનો પરિચય બનાવો.',
      'advanced_settings': 'અદ્યતન અંતરાલ સેટિંગ્સ',
      'spacing_count': 'અંતરાલ અક્ષરોની સંખ્યા: {0}',
      'spacing_note': 'નોંધ: વોટ્સએપ વેબને મોબાઇલ કરતાં વધુ અંતરાલની જરૂર છે (ડિફોલ્ટ: 1300)',
      'preset_custom': 'કસ્ટમ',
      'preset_spoiler': 'સ્પોઇલર',
      'preset_joke': 'જોક',
      'preset_quiz': 'ક્વિઝ',
      'bold_tooltip': 'બોલ્ડ',
      'italic_tooltip': 'ઇટાલિક',
      'strikethrough_tooltip': 'સ્ટ્રાઇકથ્રુ',
      'free_text_intro_label': 'પરિચય લખાણ લખો (*bold*, _italic_, ~strike~)',
      'free_text_intro_hint': 'અહીં તમારો પરિચય લખો',
      'free_text_read_more_label': 'રીડ-મોર સામગ્રી (*bold*, _italic_, ~strike~)',
      'free_text_read_more_hint': 'આ ખરેખર મજેદાર એપ છે.',
      'spoiler_q_label': 'પ્રશ્ન / સેટઅપ (દેખીતો)',
      'spoiler_q_hint': 'દા.ત. એવેન્જર્સમાં કોણ મૃત્યુ પામે છે?',
      'spoiler_a_label': 'સ્પોઇલર (છુપાયેલું)',
      'spoiler_a_hint': 'દા.ત. સ્પાઈડર-મેન ધૂળ બની જાય છે!',
      'joke_q_label': 'જોક સેટઅપ (દેખીતો)',
      'joke_q_hint': 'દા.ત. વૈજ્ઞાનિકો અણુઓ પર વિશ્વાસ કેમ નથી કરતા?',
      'joke_a_label': 'પંચલાઇન (છુપાયેલું)',
      'joke_a_hint': 'દા.ત. કારણ કે તેઓ બધું જ જાતે બનાવે છે!',
      'quiz_q_label': 'ક્વિઝ પ્રશ્ન (દેખીતો)',
      'quiz_q_hint': 'દા.ત. જાપાનની રાજધાની કઈ છે?',
      'quiz_o_label': 'વિકલ્પો (દેખીતા, વૈકલ્પિક)',
      'quiz_o_hint': 'દા.ત. A) ક્યોટો\nB) ટોક્યો\nC) ઓસાકા',
      'quiz_a_label': 'સાચો જવાબ (છુપાયેલો)',
      'quiz_a_hint': 'દા.ત. B) ટોક્યો',
      'message_preview': 'મેસેજ પ્રિવ્યુ:',
      'read_more_link': 'વધુ વાંચો',
      'button_copy': 'કોપી',
      'button_whatsapp': 'વોટ્સએપ',
      'button_templates': 'ટેમ્પલેટ્સ',
      'button_history': 'ઇતિહાસ',
      'button_save': 'સાચવો',
      'snackbar_copied': 'ક્લિપબોર્ડ પર કોપી કરાયું',
      'snackbar_wait': 'કૃપા કરીને રાહ જુઓ...',
      'snackbar_sharing': 'એપ શેર થઈ રહી છે...',
      'snackbar_sharing_template': 'ટેમ્પલેટ શેર થઈ રહ્યું છે...',
      'templates_title': 'ટેમ્પલેટ્સ',
      'search_templates': 'ટેમ્પલેટ્સ શોધો...',
      'no_templates_found': 'કોઈ ટેમ્પલેટ્સ મળ્યા નથી',
      'create_custom_template': 'કસ્ટમ ટેમ્પલેટ બનાવો',
      'custom_template_saved': 'કસ્ટમ ટેમ્પલેટ સાચવવામાં આવ્યું!',
      'fill_both_fields': 'કૃપા કરીને બંને ફીલ્ડ્સ ભરો.',
      'delete_template': 'ટેમ્પલેટ કાઢી નાખો',
      'template_deleted': 'ટેમ્પલેટ કાઢી નાખવામાં આવ્યું',
      'share_template': 'ટેમ્પલેટ શેર કરો',
      'select_language_title': 'ટેમ્પલેટ ભાષા પસંદ કરો',
      'change_language_title': 'ટેમ્પલેટ ભાષા બદલો',
      'history_title': 'ડ્રાફ્ટ ઇતિહાસ',
      'no_history_yet': 'હજી કોઈ ઇતિહાસ નથી',
      'delete_draft': 'ડ્રાફ્ટ કાઢી નાખો',
      'quiz_answer_prefix': 'જવાબ: {0}',
      'share_app_text': '*વોટ્સએપનો જાદુ અજમાવો*{0}\n\nઆ કેવું લાગ્યું? \n\nતમારા લાંબા લખાણને ટૂંકું કરો: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nબનાવનાર: https://bit.ly/read-more-whatsapp',
      'share_app': 'એપ શેર કરો',
      'category_all': 'બધા',
      'category_confessions': 'કબૂલાત (Crush)',
      'category_spoiler_alert': 'સ્પોઇલર એલર્ટ',
      'category_pranks_glitches': 'મસ્તી (Pranks)',
      'category_riddles_brainers': 'કોયડાઓ',
      'category_millennial_work': 'ઓફિસ લિંગો (Work)',
      'category_genz_sarcasm': 'રોજિંદી મસ્તી (GenZ)',
    },
    'es': {
      'app_title': 'Read More Fun',
      'app_subtitle': 'Crea cuestionarios, spoilers, chistes o presentaciones comerciales en WhatsApp con el botón "... Leer más".',
      'advanced_settings': 'Configuración avanzada de espacio',
      'spacing_count': 'Cantidad de caracteres de espacio: {0}',
      'spacing_note': 'Nota: WhatsApp Web requiere más espacios que la versión móvil (Por defecto: 1300)',
      'preset_custom': 'Personalizado',
      'preset_spoiler': 'Spoiler',
      'preset_joke': 'Chiste',
      'preset_quiz': 'Trivia',
      'bold_tooltip': 'Negrita',
      'italic_tooltip': 'Cursiva',
      'strikethrough_tooltip': 'Tachado',
      'free_text_intro_label': 'Texto de introducción (*negrita*, _cursiva_, ~tachado~)',
      'free_text_intro_hint': 'Escribe el texto de introducción aquí',
      'free_text_read_more_label': 'Contenido oculto (*negrita*, _cursiva_, ~tachado~)',
      'free_text_read_more_hint': 'Esta es una aplicación muy divertida.',
      'spoiler_q_label': 'Pregunta / Configuración (Visible)',
      'spoiler_q_hint': 'ej. ¿Quién muere en Avengers: Infinity War?',
      'spoiler_a_label': 'El Spoiler (Oculto)',
      'spoiler_a_hint': 'ej. ¡Spider-Man se convierte en polvo!',
      'joke_q_label': 'Preparación del chiste (Visible)',
      'joke_q_hint': 'ej. ¿Por qué los científicos no confían en los átomos?',
      'joke_a_label': 'Remate del chiste (Oculto)',
      'joke_a_hint': 'ej. ¡Porque lo componen todo!',
      'quiz_q_label': 'Pregunta de la trivia (Visible)',
      'quiz_q_hint': 'ej. ¿Cuál es la capital de Japón?',
      'quiz_o_label': 'Opciones (Visibles, Opcional)',
      'quiz_o_hint': 'ej. A) Kioto\nB) Tokio\nC) Osaka',
      'quiz_a_label': 'Respuesta correcta (Oculta)',
      'quiz_a_hint': 'ej. B) Tokio',
      'message_preview': 'Vista previa del mensaje:',
      'read_more_link': 'Leer más',
      'button_copy': 'Copiar',
      'button_whatsapp': 'WhatsApp',
      'button_templates': 'Plantillas',
      'button_history': 'Historial',
      'button_save': 'Guardar',
      'snackbar_copied': 'Copiado al portapapeles',
      'snackbar_wait': 'Por favor, espere...',
      'snackbar_sharing': 'Compartiendo aplicación...',
      'snackbar_sharing_template': 'Compartiendo plantilla...',
      'templates_title': 'Plantillas',
      'search_templates': 'Buscar plantillas...',
      'no_templates_found': 'No se encontraron plantillas',
      'create_custom_template': 'Crear plantilla personalizada',
      'custom_template_saved': '¡Plantilla personalizada guardada!',
      'fill_both_fields': 'Por favor complete ambos campos.',
      'delete_template': 'Eliminar plantilla',
      'template_deleted': 'Plantilla eliminada',
      'share_template': 'Compartir plantilla',
      'select_language_title': 'Seleccionar idioma de plantilla',
      'change_language_title': 'Cambiar idioma de plantilla',
      'history_title': 'Historial de borradores',
      'no_history_yet': 'Aún no hay historial',
      'delete_draft': 'Eliminar borrador',
      'quiz_answer_prefix': 'Respuesta: {0}',
      'share_app_text': '*Prueba la magia de WhatsApp*{0}\n\n¿Qué te parece? \n\nHaz tu propio texto largo a corto: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nCreado desde: https://bit.ly/read-more-whatsapp',
      'share_app': 'Compartir aplicación',
      'category_all': 'Todos',
      'category_confessions': 'Confesiones',
      'category_spoiler_alert': 'Spoilers',
      'category_pranks_glitches': 'Bromas',
      'category_riddles_brainers': 'Acertijos',
      'category_millennial_work': 'Corporativo',
      'category_genz_sarcasm': 'Sarcasmo GenZ',
    },
    'pt': {
      'app_title': 'Read More Fun',
      'app_subtitle': 'Crie testes, spoilers, piadas ou apresentações de negócios no WhatsApp com o botão "... Ler mais".',
      'advanced_settings': 'Configurações avançadas de espaçamento',
      'spacing_count': 'Contagem de caracteres de espaço: {0}',
      'spacing_note': 'Nota: O WhatsApp Web requer mais espaços que a versão móvel (Padrão: 1300)',
      'preset_custom': 'Personalizado',
      'preset_spoiler': 'Spoiler',
      'preset_joke': 'Piada',
      'preset_quiz': 'Quiz',
      'bold_tooltip': 'Negrito',
      'italic_tooltip': 'Itálico',
      'strikethrough_tooltip': 'Tachado',
      'free_text_intro_label': 'Texto de introdução (*negrito*, _itálico_, ~tachado~)',
      'free_text_intro_hint': 'Digite o texto de introdução aqui',
      'free_text_read_more_label': 'Conteúdo oculto (*negrito*, _itálico_, ~tachado~)',
      'free_text_read_more_hint': 'Este é um aplicativo muito divertido.',
      'spoiler_q_label': 'Pergunta / Preparação (Visível)',
      'spoiler_q_hint': 'ex. Quem morre em Vingadores: Guerra Infinita?',
      'spoiler_a_label': 'O Spoiler (Oculto)',
      'spoiler_a_hint': 'ex. O Homem-Aranha vira poeira!',
      'joke_q_label': 'Preparação da piada (Visível)',
      'joke_q_hint': 'ex. Por que os cientistas não confiam nos átomos?',
      'joke_a_label': 'Remate da piada (Oculto)',
      'joke_a_hint': 'ex. Porque eles compõem tudo!',
      'quiz_q_label': 'Pergunta do quiz (Visível)',
      'quiz_q_hint': 'ex. Qual é a capital do Japão?',
      'quiz_o_label': 'Opções (Visíveis, Opcional)',
      'quiz_o_hint': 'ex. A) Kyoto\nB) Tóquio\nC) Osaka',
      'quiz_a_label': 'Resposta correta (Oculta)',
      'quiz_a_hint': 'ex. B) Tóquio',
      'message_preview': 'Visualização da mensagem:',
      'read_more_link': 'Ler mais',
      'button_copy': 'Copiar',
      'button_whatsapp': 'WhatsApp',
      'button_templates': 'Modelos',
      'button_history': 'Histórico',
      'button_save': 'Salvar',
      'snackbar_copied': 'Copiado para a área de transferência',
      'snackbar_wait': 'Por favor, aguarde...',
      'snackbar_sharing': 'Compartilhando aplicativo...',
      'snackbar_sharing_template': 'Compartilhando modelo...',
      'templates_title': 'Modelos',
      'search_templates': 'Buscar modelos...',
      'no_templates_found': 'Nenhum modelo encontrado',
      'create_custom_template': 'Criar modelo personalizado',
      'custom_template_saved': '¡Modelo personalizado salvo!',
      'fill_both_fields': 'Por favor preencha ambos os campos.',
      'delete_template': 'Excluir modelo',
      'template_deleted': 'Modelo excluído',
      'share_template': 'Compartilhar modelo',
      'select_language_title': 'Selecionar idioma do modelo',
      'change_language_title': 'Alterar idioma do modelo',
      'history_title': 'Histórico de rascunhos',
      'no_history_yet': 'Ainda não há histórico',
      'delete_draft': 'Excluir rascunho',
      'quiz_answer_prefix': 'Resposta: {0}',
      'share_app_text': '*Experimente a magia do WhatsApp*{0}\n\nO que achou? \n\nFaça seu próprio texto longo ficar curto: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nCriado a partir de: https://bit.ly/read-more-whatsapp',
      'share_app': 'Compartilhando aplicativo',
      'category_all': 'Todos',
      'category_confessions': 'Confissões',
      'category_spoiler_alert': 'Spoilers',
      'category_pranks_glitches': 'Pegadinhas',
      'category_riddles_brainers': 'Charadas',
      'category_millennial_work': 'Corporativo',
      'category_genz_sarcasm': 'Sarcasmo GenZ',
    },
    'zh': {
      'app_title': '阅读更多乐趣',
      'app_subtitle': '利用“... 阅读更多”按钮，在微信/WhatsApp中创建更长消息的问答、剧透、笑话或商业介绍。',
      'advanced_settings': '高级间距设置',
      'spacing_count': '空格字符数: {0}',
      'spacing_note': '注意：网页版比手机版需要更多空格（默认值：1300）',
      'preset_custom': '自定义',
      'preset_spoiler': '剧透',
      'preset_joke': '笑话',
      'preset_quiz': '问答',
      'bold_tooltip': '加粗',
      'italic_tooltip': '斜体',
      'strikethrough_tooltip': '删除线',
      'free_text_intro_label': '输入引入文本（*加粗*、_斜体_、~删除线~）',
      'free_text_intro_hint': '在此输入引入文本',
      'free_text_read_more_label': '“阅读更多”后内容（*加粗*、_斜体_、~删除线~）',
      'free_text_read_more_hint': '这是一个非常有趣的应用程序。',
      'spoiler_q_label': '问题/背景（可见）',
      'spoiler_q_hint': '例如：复仇者联盟3里谁死了？',
      'spoiler_a_label': '剧透内容（隐藏）',
      'spoiler_a_hint': '例如：蜘蛛侠变成了灰烬！',
      'joke_q_label': '笑话铺垫（可见）',
      'joke_q_hint': '例如：为什么科学家不信任原子？',
      'joke_a_label': '笑话包袱（隐藏）',
      'joke_a_hint': '例如：因为它们构成了万物！',
      'quiz_q_label': '问答题目（可见）',
      'quiz_q_hint': '例如：日本的首都是哪里？',
      'quiz_o_label': '选项（可见，可选）',
      'quiz_o_hint': '例如：A) 京都\nB) 东京\nC) 大阪',
      'quiz_a_label': '正确答案（隐藏）',
      'quiz_a_hint': '例如：B) 东京',
      'message_preview': '消息预览:',
      'read_more_link': '阅读更多',
      'button_copy': '复制',
      'button_whatsapp': '微信/社交分享',
      'button_templates': '模板库',
      'button_history': '历史草稿',
      'button_save': '保存',
      'snackbar_copied': '已复制到剪贴板',
      'snackbar_wait': '请稍候...',
      'snackbar_sharing': '正在分享应用...',
      'snackbar_sharing_template': '正在分享模板...',
      'templates_title': '模板库',
      'search_templates': '搜索模板...',
      'no_templates_found': '没有找到模板',
      'create_custom_template': '创建自定义模板',
      'custom_template_saved': '自定义模板保存成功！',
      'fill_both_fields': '请填写所有输入框。',
      'delete_template': '删除模板',
      'template_deleted': '模板已删除',
      'share_template': '分享模板',
      'select_language_title': '选择模板语言',
      'change_language_title': '修改模板语言',
      'history_title': '历史草稿箱',
      'no_history_yet': '暂无历史记录',
      'delete_draft': '删除草稿',
      'quiz_answer_prefix': '答案：{0}',
      'share_app_text': '*体验社群黑科技魔法*{0}\n\n感觉怎么样？\n\n一键制作你的遮罩式长文本：https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\n制作自: https://bit.ly/read-more-whatsapp',
      'share_app': '分享应用',
      'category_all': '全部',
      'category_confessions': '表白 (Crush)',
      'category_spoiler_alert': '剧透预警',
      'category_pranks_glitches': '恶作剧 (Pranks)',
      'category_riddles_brainers': '脑筋急转弯',
      'category_millennial_work': '职场黑话 (Work)',
      'category_genz_sarcasm': 'GenZ日常讽刺',
    },
    'fr': {
      'app_title': 'Lire Plus Amusant',
      'app_subtitle': 'Créez des quiz, des spoilers, des blagues ou des présentations d\'affaires WhatsApp avec le bouton « ... Lire la suite ».',
      'advanced_settings': 'Paramètres d\'espacement avancés',
      'spacing_count': 'Nombre de caractères d\'espacement: {0}',
      'spacing_note': 'Note: WhatsApp Web nécessite plus d\'espaces que la version mobile (Par défaut : 1300)',
      'preset_custom': 'Personnalisé',
      'preset_spoiler': 'Spoiler',
      'preset_joke': 'Blague',
      'preset_quiz': 'Quiz',
      'bold_tooltip': 'Gras',
      'italic_tooltip': 'Italique',
      'strikethrough_tooltip': 'Barré',
      'free_text_intro_label': 'Texte d\'introduction (*gras*, _italique_, ~barré~)',
      'free_text_intro_hint': 'Tapez le texte d\'introduction ici',
      'free_text_read_more_label': 'Contenu caché (*gras*, _italique_, ~barré~)',
      'free_text_read_more_hint': 'C\'est une application très amusante.',
      'spoiler_q_label': 'Question / Contexte (Visuel)',
      'spoiler_q_hint': 'ex: Qui meurt dans Avengers : Infinity War ?',
      'spoiler_a_label': 'Le Spoiler (Caché)',
      'spoiler_a_hint': 'ex: Spider-Man tombe en poussière !',
      'joke_q_label': 'Introduction de blague (Visuel)',
      'joke_q_hint': 'ex: Pourquoi les scientifiques ne font pas confiance aux atomes ?',
      'joke_a_label': 'Chute (Caché)',
      'joke_a_hint': 'ex: Parce qu\'ils composent tout !',
      'quiz_q_label': 'Question du quiz (Visuel)',
      'quiz_q_hint': 'ex: Quelle est la capitale du Japon ?',
      'quiz_o_label': 'Options (Visuel, Optionnel)',
      'quiz_o_hint': 'ex: A) Kyoto\nB) Tokyo\nC) Osaka',
      'quiz_a_label': 'Bonne réponse (Caché)',
      'quiz_a_hint': 'ex: B) Tokyo',
      'message_preview': 'Aperçu du message :',
      'read_more_link': 'Lire la suite',
      'button_copy': 'Copier',
      'button_whatsapp': 'WhatsApp',
      'button_templates': 'Modèles',
      'button_history': 'Historique',
      'button_save': 'Enregistrer',
      'snackbar_copied': 'Copié dans le presse-papiers',
      'snackbar_wait': 'Veuillez patienter...',
      'snackbar_sharing': 'Partage de l\'application...',
      'snackbar_sharing_template': 'Partage du modèle...',
      'templates_title': 'Modèles',
      'search_templates': 'Rechercher des modèles...',
      'no_templates_found': 'Aucun modèle trouvé',
      'create_custom_template': 'Créer un modèle personnalisé',
      'custom_template_saved': 'Modèle personnalisé enregistré !',
      'fill_both_fields': 'Veuillez remplir les deux champs.',
      'delete_template': 'Supprimer le modèle',
      'template_deleted': 'Modèle supprimé',
      'share_template': 'Partager le modèle',
      'select_language_title': 'Choisir la langue du modèle',
      'change_language_title': 'Changer la langue du modèle',
      'history_title': 'Historique des brouillons',
      'no_history_yet': 'Aucun historique pour le moment',
      'delete_draft': 'Supprimer le brouillon',
      'quiz_answer_prefix': 'Réponse : {0}',
      'share_app_text': '*Essayez la magie de WhatsApp*{0}\n\nComment le trouvez-vous ? \n\nRaccourcissez vos longs textes : https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nCréé avec : https://bit.ly/read-more-whatsapp',
      'share_app': 'Partager l\'application',
      'category_all': 'Tout',
      'category_confessions': 'Confessions (Crush)',
      'category_spoiler_alert': 'Alerte Spoiler',
      'category_pranks_glitches': 'Farces & Bugs',
      'category_riddles_brainers': 'Énigmes & Logique',
      'category_millennial_work': 'Langage de Bureau',
      'category_genz_sarcasm': 'Sarcasme GenZ',
    },
    'ar': {
      'app_title': 'قراءة المزيد متعة',
      'app_subtitle': 'أنشئ اختبارات أو حرق أحداث أو نكات أو مقدمات أعمال في WhatsApp باستخدام زر "... قراءة المزيد".',
      'advanced_settings': 'إعدادات المسافة المتقدمة',
      'spacing_count': 'عدد أحرف المسافة: {0}',
      'spacing_note': 'ملاحظة: يتطلب واتساب ويب مسافات أكثر من الهاتف المحمول (الافتراضي: 1300)',
      'preset_custom': 'مخصص',
      'preset_spoiler': 'حرق أحداث',
      'preset_joke': 'نكتة',
      'preset_quiz': 'اختبار',
      'bold_tooltip': 'عريض',
      'italic_tooltip': 'مائل',
      'strikethrough_tooltip': 'يتوسطه خط',
      'free_text_intro_label': 'أدخل النص التعريفي (*عريض*، _مائل_، ~يتوسطه خط~)',
      'free_text_intro_hint': 'اكتب النص التعريفي هنا',
      'free_text_read_more_label': 'محتوى "قراءة المزيد" (*عريض*، _مائل_، ~يتوسطه خط~)',
      'free_text_read_more_hint': 'هذا تطبيق مضحك للغاية.',
      'spoiler_q_label': 'السؤال / الإعداد (مرئي)',
      'spoiler_q_hint': 'مثال: من يموت في فيلم المنتقمون؟',
      'spoiler_a_label': 'الحرق (مخفي)',
      'spoiler_a_hint': 'مثال: يتحول الرجل العنكبوت إلى غبار!',
      'joke_q_label': 'مقدمة النكتة (مرئي)',
      'joke_q_hint': 'مثال: لماذا لا يثق العلماء بالذرات؟',
      'joke_a_label': 'خاتمة النكتة (مخفي)',
      'joke_a_hint': 'مثال: لأنها تشكل كل شيء!',
      'quiz_q_label': 'سؤال الاختبار (مرئي)',
      'quiz_q_hint': 'مثال: ما هي عاصمة اليابان؟',
      'quiz_o_label': 'الخيارات (مرئي، اختياري)',
      'quiz_o_hint': 'مثال: A) كيوتو\nB) طوكيو\nC) أوساكا',
      'quiz_a_label': 'الإجابة الصحيحة (مخفي)',
      'quiz_a_hint': 'مثال: B) طوكيو',
      'message_preview': 'معاينة الرسالة:',
      'read_more_link': 'قراءة المزيد',
      'button_copy': 'نسخ',
      'button_whatsapp': 'واتساب',
      'button_templates': 'القوالب',
      'button_history': 'السجل',
      'button_save': 'حفظ',
      'snackbar_copied': 'تم النسخ إلى الحافظة',
      'snackbar_wait': 'يرجى الانتظار...',
      'snackbar_sharing': 'جاري مشاركة التطبيق...',
      'snackbar_sharing_template': 'جاري مشاركة القالب...',
      'templates_title': 'القوالب',
      'search_templates': 'البحث في القوالب...',
      'no_templates_found': 'لم يتم العثور على أي قوالب',
      'create_custom_template': 'إنشاء قالب مخصص',
      'custom_template_saved': 'تم حفظ القالب المخصص بنجاح!',
      'fill_both_fields': 'يرجى ملء كلا الحقلين.',
      'delete_template': 'حذف القالب',
      'template_deleted': 'تم حذف القالب',
      'share_template': 'مشاركة القالب',
      'select_language_title': 'اختر لغة القوالب',
      'change_language_title': 'تغيير لغة القوالب',
      'history_title': 'سجل المسودات',
      'no_history_yet': 'لا يوجد سجل بعد',
      'delete_draft': 'حذف المسودة',
      'quiz_answer_prefix': 'الإجابة: {0}',
      'share_app_text': '*جرب سحر واتساب*{0}\n\nما رأيك بها؟ \n\nاجعل نصك الطويل قصيراً: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nتم إنشاؤه عبر: https://bit.ly/read-more-whatsapp',
      'share_app': 'مشاركة التطبيق',
      'category_all': 'الكل',
      'category_confessions': 'اعترافات (Crush)',
      'category_spoiler_alert': 'حرق أحداث',
      'category_pranks_glitches': 'مقالب وأعطال',
      'category_riddles_brainers': 'ألغاز وذكاء',
      'category_millennial_work': 'لغة العمل',
      'category_genz_sarcasm': 'سخرية جيل Z',
    },
    'bn': {
      'app_title': 'রীড মোর ফান',
      'app_subtitle': 'হোয়াটসঅ্যাপে দীর্ঘ বার্তাগুলির সাথে "... Read more" বোতাম যোগ করে মজাদার ধাঁধা, কৌতুক বা ব্যবসায়িক পরিচয় তৈরি করুন।',
      'advanced_settings': 'উন্নত স্পেসিং সেটিংস',
      'spacing_count': 'স্পেস অক্ষর সংখ্যা: {0}',
      'spacing_note': 'দ্রষ্টব্য: হোয়াটসঅ্যাপ ওয়েবের মোবাইলের চেয়ে বেশি স্পেস প্রয়োজন (ডিফল্ট: ১৩০০)',
      'preset_custom': 'কাস্টম',
      'preset_spoiler': 'স্পয়লার',
      'preset_joke': 'কৌতুক',
      'preset_quiz': 'কুইজ',
      'bold_tooltip': 'বোল্ড',
      'italic_tooltip': 'ইটালিক',
      'strikethrough_tooltip': 'স্ট্রাইক থ্রু',
      'free_text_intro_label': 'ভূমিকা লিখুন (*bold*, _italic_, ~strike~)',
      'free_text_intro_hint': 'এখানে ভূমিকা লিখুন',
      'free_text_read_more_label': 'রিড-মোর কন্টেন্ট (*bold*, _italic_, ~strike~)',
      'free_text_read_more_hint': 'এটি একটি সত্যিই মজার অ্যাপ।',
      'spoiler_q_label': 'প্রশ্ন / সেটআপ (দৃশ্যমান)',
      'spoiler_q_hint': 'যেমন: অ্যাভেঞ্জার্সে কে মারা যায়?',
      'spoiler_a_label': 'স্পয়লার (লুকানো)',
      'spoiler_a_hint': 'যেমন: স্পাইডার ম্যান ধুলো হয়ে যায়!',
      'joke_q_label': 'কৌতুক সেটআপ (দৃশ্যমান)',
      'joke_q_hint': 'যেমন: বিজ্ঞানীরা কেন পরমাণু বিশ্বাস করেন না?',
      'joke_a_label': 'পঞ্চলাইন (লুকানো)',
      'joke_a_hint': 'যেমন: কারণ তারা সবকিছু তৈরি করে!',
      'quiz_q_label': 'কুইজ প্রশ্ন (দৃশ্যমান)',
      'quiz_q_hint': 'যেমন: জাপানের রাজধানী কী?',
      'quiz_o_label': 'বিকল্প (দৃশ্যমান, ঐচ্ছিক)',
      'quiz_o_hint': 'যেমন: A) কিয়োটো\nB) টোকিও\nC) ওসাকা',
      'quiz_a_label': 'সঠিক উত্তর (লুকানো)',
      'quiz_a_hint': 'যেমন: B) টোকিও',
      'message_preview': 'মেসেজ প্রিভিউ:',
      'read_more_link': 'আরো পড়ুন',
      'button_copy': 'কপি',
      'button_whatsapp': 'হোয়াটসঅ্যাপ',
      'button_templates': 'টেম্পলেট',
      'button_history': 'ইতিহাস',
      'button_save': 'সংরক্ষণ',
      'snackbar_copied': 'ক্লিপবোর্ডে কপি করা হয়েছে',
      'snackbar_wait': 'অনুগ্রহ করে অপেক্ষা করুন...',
      'snackbar_sharing': 'অ্যাপ্লিকেশন শেয়ার করা হচ্ছে...',
      'snackbar_sharing_template': 'টেম্পলেট শেয়ার করা হচ্ছে...',
      'templates_title': 'টেম্পলেট',
      'search_templates': 'টেম্পলেট খুঁজুন...',
      'no_templates_found': 'কোন টেম্পলেট পাওয়া যায়নি',
      'create_custom_template': 'কাস্টম টেম্পলেট তৈরি করুন',
      'custom_template_saved': 'কাস্টম টেম্পলেট সংরক্ষিত হয়েছে!',
      'fill_both_fields': 'অনুগ্রহ করে উভয় ক্ষেত্র পূরণ করুন।',
      'delete_template': 'টেম্পলেট মুছুন',
      'template_deleted': 'টেম্পলেট মুছে ফেলা হয়েছে',
      'share_template': 'টেম্পলেট শেয়ার করুন',
      'select_language_title': 'টেম্পলেটের ভাষা নির্বাচন করুন',
      'change_language_title': 'টেম্পলেটের ভাষা পরিবর্তন করুন',
      'history_title': 'ড্রাফট ইতিহাস',
      'no_history_yet': 'এখনো কোনো ইতিহাস নেই',
      'delete_draft': 'ড্রাফট মুছুন',
      'quiz_answer_prefix': 'উত্তর: {0}',
      'share_app_text': '*হোয়াটসঅ্যাপের জাদু ব্যবহার করে দেখুন*{0}\n\nকেমন লেগেছে? \n\nআপনার বড় লেখাটি ছোট করুন: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nতৈরি করা হয়েছে: https://bit.ly/read-more-whatsapp',
      'share_app': 'অ্যাপ্লিকেশন শেয়ার করুন',
      'category_all': 'সব',
      'category_confessions': 'স্বীকারোক্তি (Crush)',
      'category_spoiler_alert': 'স্পয়লার সতর্কতা',
      'category_pranks_glitches': 'কৌতুক ও গ্লিচ',
      'category_riddles_brainers': 'ধাঁধা ও বুদ্ধির খেলা',
      'category_millennial_work': 'অফিসের ভাষা',
      'category_genz_sarcasm': 'GenZ ব্যঙ্গ',
    },
    'ru': {
      'app_title': 'Читать Еще Веселее',
      'app_subtitle': 'Создавайте викторины, спойлеры, шутки или визитки в WhatsApp с кнопкой «... Читать далее».',
      'advanced_settings': 'Расширенные настройки интервалов',
      'spacing_count': 'Количество символов интервала: {0}',
      'spacing_note': 'Примечание: для WhatsApp Web требуется больше пробелов, чем для мобильных устройств (по умолчанию: 1300)',
      'preset_custom': 'Свой текст',
      'preset_spoiler': 'Спойлер',
      'preset_joke': 'Шутка',
      'preset_quiz': 'Опрос',
      'bold_tooltip': 'Жирный',
      'italic_tooltip': 'Курсив',
      'strikethrough_tooltip': 'Зачеркнутый',
      'free_text_intro_label': 'Введите вводный текст (*жирный*, _курсив_, ~зачеркнутый~)',
      'free_text_intro_hint': 'Введите вводную часть здесь',
      'free_text_read_more_label': 'Скрытый контент (*жирный*, _курсив_, ~зачеркнутый~)',
      'free_text_read_more_hint': 'Это очень веселое приложение.',
      'spoiler_q_label': 'Вопрос / Подводка (Видимый)',
      'spoiler_q_hint': 'напр. Кто умирает в Мстителях: Война бесконечности?',
      'spoiler_a_label': 'Спойлер (Скрытый)',
      'spoiler_a_hint': 'напр. Человек-паук превращается в пыль!',
      'joke_q_label': 'Начало шутки (Видимый)',
      'joke_q_hint': 'напр. Почему ученые не доверяют атомам?',
      'joke_a_label': 'Развязка (Скрытый)',
      'joke_a_hint': 'напр. Потому что они всё составляют!',
      'quiz_q_label': 'Вопрос опроса (Видимый)',
      'quiz_q_hint': 'напр. Какая столица Японии?',
      'quiz_o_label': 'Варианты (Видимые, Необязательно)',
      'quiz_o_hint': 'напр. А) Киото\nБ) Токио\nВ) Осака',
      'quiz_a_label': 'Правильный ответ (Скрытый)',
      'quiz_a_hint': 'напр. Б) Токио',
      'message_preview': 'Предварительный просмотр сообщения:',
      'read_more_link': 'Читать далее',
      'button_copy': 'Копировать',
      'button_whatsapp': 'WhatsApp',
      'button_templates': 'Шаблоны',
      'button_history': 'История',
      'button_save': 'Сохранить',
      'snackbar_copied': 'Скопировано в буфер обмена',
      'snackbar_wait': 'Пожалуйста, подождите...',
      'snackbar_sharing': 'Поделиться приложением...',
      'snackbar_sharing_template': 'Поделиться шаблоном...',
      'templates_title': 'Шаблоны',
      'search_templates': 'Поиск шаблонов...',
      'no_templates_found': 'Шаблоны не найдены',
      'create_custom_template': 'Создать свой шаблон',
      'custom_template_saved': 'Свой шаблон сохранен!',
      'fill_both_fields': 'Пожалуйста, заполните оба поля.',
      'delete_template': 'Удалить шаблон',
      'template_deleted': 'Шаблон удален',
      'share_template': 'Поделиться шаблоном',
      'select_language_title': 'Выберите язык шаблонов',
      'change_language_title': 'Сменить язык шаблонов',
      'history_title': 'История черновиков',
      'no_history_yet': 'Истории пока нет',
      'delete_draft': 'Удалить черновик',
      'quiz_answer_prefix': 'Ответ: {0}',
      'share_app_text': '*Испытайте магию WhatsApp*{0}\n\nКак вам? \n\nСделайте свой длинный текст коротким: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nСоздано через: https://bit.ly/read-more-whatsapp',
      'share_app': 'Поделиться приложением',
      'category_all': 'Все',
      'category_confessions': 'Признания (Crush)',
      'category_spoiler_alert': 'Спойлеры',
      'category_pranks_glitches': 'Розыгрыши и Баги',
      'category_riddles_brainers': 'Загадки и Ребусы',
      'category_millennial_work': 'Офисный Сленг',
      'category_genz_sarcasm': 'Сарказм Зумеров',
    },
    'ur': {
      'app_title': 'ریڈ مور فن',
      'app_subtitle': 'واٹس ایپ پر طویل پیغامات کے ساتھ "... Read more" بٹن جوڑ کر تفریحی پہیلیاں، لطیفے یا کاروباری تعارف بنائیں۔',
      'advanced_settings': 'جدید اسپییسنگ ترتیبات',
      'spacing_count': 'اسپیس حروف کی تعداد: {0}',
      'spacing_note': 'نوٹ: واٹس ایپ ویب کو موبائل کے مقابلے میں زیادہ اسپیسز کی ضرورت ہوتی ہے (ڈیفالٹ: 1300)',
      'preset_custom': 'مخصوص',
      'preset_spoiler': 'حرق',
      'preset_joke': 'لطیفہ',
      'preset_quiz': 'سوال نامہ',
      'bold_tooltip': 'جلی',
      'italic_tooltip': 'ترچھا',
      'strikethrough_tooltip': 'خط کشیدہ',
      'free_text_intro_label': 'تعارف لکھیں (*bold*, _italic_, ~strike~)',
      'free_text_intro_hint': 'یہاں اپنا تعارف درج کریں',
      'free_text_read_more_label': 'ریڈ مور مواد (*bold*, _italic_, ~strike~)',
      'free_text_read_more_hint': 'یہ واقعی ایک دلچسپ ایپ ہے۔',
      'spoiler_q_label': 'سوال / سیٹ اپ (ظاہر ہے)',
      'spoiler_q_hint': 'مثال: ایونجرز میں کون مرتا ہے؟',
      'spoiler_a_label': 'راز کی بات (چھپی ہوئی ہے)',
      'spoiler_a_hint': 'مثال: اسپائیڈر مین مٹی میں تبدیل ہو جاتا ہے!',
      'joke_q_label': 'لطیفے کا سیٹ اپ (ظاہر ہے)',
      'joke_q_hint': 'مثال: سائنسدان ایٹموں پر بھروسہ کیوں نہیں کرتے؟',
      'joke_a_label': 'لطیفے کا اخراج (چھپا ہوا ہے)',
      'joke_a_hint': 'مثال: کیونکہ وہ سب کچھ خود بناتے ہیں!',
      'quiz_q_label': 'سوال نامہ کا سوال (ظاہر ہے)',
      'quiz_q_hint': 'مثال: جاپان کا دارالحکومت کیا ہے؟',
      'quiz_o_label': 'آپشنز (ظاہر ہے، اختیاری)',
      'quiz_o_hint': 'مثال: A) کیوٹو\nB) ٹوکیو\nC) اوساکا',
      'quiz_a_label': 'درست جواب (چھپا ہوا ہے)',
      'quiz_a_hint': 'مثال: B) ٹوکیو',
      'message_preview': 'پیغام کا پیش نظارہ:',
      'read_more_link': 'مزید پڑھیں',
      'button_copy': 'کاپی',
      'button_whatsapp': 'واٹس ایپ',
      'button_templates': 'ٹیمپلیٹس',
      'button_history': 'سجل',
      'button_save': 'محفوظ کریں',
      'snackbar_copied': 'کلپ بورڈ پر کاپی ہو گیا',
      'snackbar_wait': 'براہ کرم انتظار کریں...',
      'snackbar_sharing': 'ایپ شیئر کی جا رہی ہے...',
      'snackbar_sharing_template': 'ٹیمپلیٹ شیयर کیا جا رہا ہے...',
      'templates_title': 'ٹیمپلیٹس',
      'search_templates': 'ٹیمپلیٹس تلاش کریں...',
      'no_templates_found': 'کوئی ٹیمپلیٹ نہیں ملا',
      'create_custom_template': 'اپنی مرضی کا ٹیمپلیٹ بنائیں',
      'custom_template_saved': 'اپنی مرضی کا ٹیمپلیٹ محفوظ کر لیا گیا!',
      'fill_both_fields': 'براہ کرم دونوں خانے پُر کریں۔',
      'delete_template': 'ٹیمپلیٹ حذف کریں',
      'template_deleted': 'ٹیمپلیٹ حذف کر دیا گیا',
      'share_template': 'ٹیمپلیٹ شیئر کریں',
      'select_language_title': 'ٹیمپلیٹ کی زبان منتخب کریں',
      'change_language_title': 'ٹیمپلیٹ کی زبان تبدیل کریں',
      'history_title': 'ڈرافٹ سجل',
      'no_history_yet': 'ابھی تک کوئی سجل نہیں',
      'delete_draft': 'ڈرافٹ حذف کریں',
      'quiz_answer_prefix': 'جواب: {0}',
      'share_app_text': '*واٹس ایپ کے جادو کو آزمائیں*{0}\n\nیہ کیسا لگا؟ \n\nاپنے طویل متن کو مختصر بنائیں: https://bit.ly/read-more-whatsapp',
      'share_template_text': '{0}{1}{2}\n\nتخلیق کار: https://bit.ly/read-more-whatsapp',
      'share_app': 'ایپ شیئر کریں',
      'category_all': 'تمام',
      'category_confessions': 'اعترافات (Crush)',
      'category_spoiler_alert': 'حرق احادیث',
      'category_pranks_glitches': 'شرارتیں اور گلیچ',
      'category_riddles_brainers': 'پہیلیاں اور دماغی کھیلیں',
      'category_millennial_work': 'دفتر کی گفتگو',
      'category_genz_sarcasm': 'روزمرہ سخرية',
    },
  };

  static String getValue(String langCode, String key) {
    // Falls back to English if target language or key doesn't exist.
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
