name: Build APK

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: macos-latest  # Keep as macOS if needed for iOS builds
    
    steps:
      - uses: actions/checkout@v4

      # 1. Explicit Flutter Installation (Recommended)
      - name: Install Flutter 3.32.2
        run: |
          mkdir -p $HOME/app/flutter_sdk
          wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.32.2-stable.zip
          unzip -q flutter_macos_3.32.2-stable.zip -d $HOME/app/flutter_sdk
          echo "FLUTTER_ROOT=$HOME/app/flutter_sdk/flutter" >> $GITHUB_ENV
          echo "$FLUTTER_ROOT/bin" >> $GITHUB_PATH

      # 2. Alternative: Using flutter-action with correct version
      # - uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable
      #     flutter-version: 3.32.2  # Verify this version exists in the action

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'  # Updated for Flutter 3.32 compatibility

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
